/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.restaurantFrame;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Employee;
import model.Restaurant;
import model.EateryEnterprise;
import model.Food;

/**
 *
 * @author ktkir
 */
public class employeeManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form employeeManagePanel
     */
    private EateryEnterprise eatery;
    private int currentRestarauntId;
    private Restaurant currentRestaraunt;
    private List<Employee> currentEmployeeList;
    public employeeManagePanel(EateryEnterprise eatery,int restarauntId ) {
        initComponents();
        this.eatery=eatery;
        this.currentRestarauntId=restarauntId;
        this.currentRestaraunt=eatery.getRestaurantById(restarauntId);
        this.currentEmployeeList=eatery.getEmployeesByRestaurant(restarauntId);
        displayEmployeeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textEmployeeId = new javax.swing.JTextField();
        updateFood = new javax.swing.JButton();
        deleteEmployee = new javax.swing.JButton();
        btnAddEmployee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        confirmUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mngEmployeeTable = new javax.swing.JTable();
        searchValue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textEmployeeName = new javax.swing.JTextField();
        roleDropdown = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        editEmployeeName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        editRole = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Employee");

        textEmployeeId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        updateFood.setBackground(new java.awt.Color(255, 255, 0));
        updateFood.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateFood.setText("Update Employee");
        updateFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFoodActionPerformed(evt);
            }
        });

        deleteEmployee.setBackground(new java.awt.Color(255, 255, 0));
        deleteEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteEmployee.setText("Delete Employee");
        deleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeActionPerformed(evt);
            }
        });

        btnAddEmployee.setBackground(new java.awt.Color(255, 255, 0));
        btnAddEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddEmployee.setText("Add Employee To Restaraunt");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Employee Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Search");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Employee Id");

        confirmUpdate.setBackground(new java.awt.Color(255, 255, 0));
        confirmUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmUpdate.setText("Confirm Update");
        confirmUpdate.setEnabled(false);
        confirmUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmUpdateActionPerformed(evt);
            }
        });

        mngEmployeeTable.setBackground(new java.awt.Color(255, 255, 0));
        mngEmployeeTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mngEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Id", "Employee Name", "Role"
            }
        ));
        jScrollPane1.setViewportView(mngEmployeeTable);

        searchValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchValueActionPerformed(evt);
            }
        });
        searchValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchValueKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchValueKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Role");

        textEmployeeName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeNameActionPerformed(evt);
            }
        });

        roleDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu Manager", "Order Manager" }));
        roleDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleDropdownActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Role");

        editEmployeeName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Employee Name");

        editRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu Manager", "Order Manager" }));
        editRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1588, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editRole, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editEmployeeName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddEmployee)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(50, 50, 50)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(roleDropdown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEmployeeName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEmployeeId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(deleteEmployee)
                        .addGap(47, 47, 47)
                        .addComponent(updateFood))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(confirmUpdate)))
                .addGap(580, 580, 580))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roleDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddEmployee)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEmployee)
                    .addComponent(updateFood))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(editEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmUpdate)
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFoodActionPerformed
        int col= 0;
        int row=mngEmployeeTable.getSelectedRow();
        int employeeId= Integer.parseInt(mngEmployeeTable.getModel().getValueAt(row, col).toString());

        if (row < 0) {
            JOptionPane.showMessageDialog(this, "You should select atleast 1 row to update!");
        } else {
            editEmployeeName.setEnabled(true);
            editRole.setEnabled(true);
            confirmUpdate.setEnabled(true);
            Employee emp  =eatery.getEmployeeId(employeeId);
            editEmployeeName.setText(emp.getName());
             editRole.setSelectedItem(emp.getRole());
        }
    }//GEN-LAST:event_updateFoodActionPerformed

       private void displayEmployeeTable() 
     {
         editEmployeeName.setEnabled(false);
         editRole.setSelectedItem(null);
         editRole.setEnabled(false);
         confirmUpdate.setEnabled(false);
         textEmployeeId.setText("");
         textEmployeeName.setText("");
         roleDropdown.setSelectedItem(null);
         mngEmployeeTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel tableModel = (DefaultTableModel) mngEmployeeTable.getModel();
        tableModel.setRowCount(0);
        if (currentEmployeeList!=null) {
            for (int i = 0; i < currentEmployeeList.size(); i++) {
                Employee emp = currentEmployeeList.get(i);
                Object[] tableRow = new Object[10];
                tableRow[0] = emp.getEmployeeId();
                tableRow[1]= emp.getName();
                tableRow[2] = emp.getRole();
                tableModel.addRow(tableRow);
            }
        }
         
     }
    
    private void deleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeActionPerformed
        // TODO add your handling code here:
        int col=0;
        int row=mngEmployeeTable.getSelectedRow();
        int employeeId= Integer.parseInt(mngEmployeeTable.getModel().getValueAt(row, col).toString());
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "You should select atleast 1 row to delete!");
        }
        else
        {
            eatery.removeEmployeeFromRestaurant(currentRestarauntId, employeeId);
            currentEmployeeList=eatery.getEmployeesByRestaurant(currentRestarauntId);
            displayEmployeeTable();
            JOptionPane.showMessageDialog(this, "Employee Deleted");
        }

    }//GEN-LAST:event_deleteEmployeeActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
        if(!textEmployeeId.getText().equals("") && !textEmployeeName.getText().equals("") && roleDropdown.getSelectedItem()!=null)
        {
            if(!textEmployeeId.getText().matches("[0-9]+"))
            {
                JOptionPane.showMessageDialog(this, "Restaraunt id should be all numbers!");
            }
            
            if(!eatery.isEmployeeIdUnique(Integer.parseInt(textEmployeeId.getText())))
            {
                JOptionPane.showMessageDialog(this, "Employee Id should be unique!");
            }

            else if(textEmployeeId.getText().matches("[0-9]+") && eatery.isEmployeeIdUnique(Integer.parseInt(textEmployeeId.getText())))
            {
                eatery.addEmployeeToRestaurant(textEmployeeName.getText(), Integer.parseInt(textEmployeeId.getText()) ,currentRestarauntId, roleDropdown.getSelectedItem().toString());
                JOptionPane.showMessageDialog(this, "Employee added to Restaraunt's menu!");
                displayEmployeeTable();
            }

        }
        else
        JOptionPane.showMessageDialog(this, "Fill all the details to create a Restaraunt!");
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void confirmUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmUpdateActionPerformed
        // TODO add your handling code here:
        int col= 0;
        int row=mngEmployeeTable.getSelectedRow();
        int employeeId= Integer.parseInt(mngEmployeeTable.getModel().getValueAt(row, col).toString());
        if(!editEmployeeName.getText().equals("") && editRole.getSelectedItem()!=null)
        {
           eatery.updateEmployee(currentRestarauntId, employeeId, editEmployeeName.getText(), editRole.getSelectedItem().toString());
            editEmployeeName.setText("");
            editEmployeeName.setEnabled(false);
            editRole.setSelectedItem(null);
            editRole.setEnabled(false);
            displayEmployeeTable();

        }
        else
        JOptionPane.showMessageDialog(this, "Fill all the details to update Food");
    }//GEN-LAST:event_confirmUpdateActionPerformed

    private void searchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchValueActionPerformed

    private void searchValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchValueKeyPressed
        // TODO add your handling code here:
        search(searchValue.getText());
    }//GEN-LAST:event_searchValueKeyPressed

    private void searchValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchValueKeyReleased
        // TODO add your handling code here:
        search(searchValue.getText());
    }//GEN-LAST:event_searchValueKeyReleased

       public void search(String str) {
        DefaultTableModel model = (DefaultTableModel) mngEmployeeTable.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        mngEmployeeTable.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
       }
    
    private void textEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeNameActionPerformed

    private void roleDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleDropdownActionPerformed

    private void editEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeNameActionPerformed

    private void editRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton confirmUpdate;
    private javax.swing.JButton deleteEmployee;
    private javax.swing.JTextField editEmployeeName;
    private javax.swing.JComboBox<String> editRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mngEmployeeTable;
    private javax.swing.JComboBox<String> roleDropdown;
    private javax.swing.JTextField searchValue;
    private javax.swing.JTextField textEmployeeId;
    private javax.swing.JTextField textEmployeeName;
    private javax.swing.JButton updateFood;
    // End of variables declaration//GEN-END:variables
}
