/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.restaurantFrame;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.EateryEnterprise;
import model.Employee;
import model.Food;
import model.Order;

/**
 *
 * @author BARATHI
 */
public class orderManagerPanel extends javax.swing.JFrame {

    /**
     * Creates new form orderManagerPanel
     */
    EateryEnterprise eatery;
    int currentRestaurantId;
    private ArrayList<Order> resOrders;
    private List<Food> orderedFood;
    
    public orderManagerPanel(EateryEnterprise eatery,int restaurantId) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.eatery=eatery;
        this.currentRestaurantId=restaurantId;
        resOrders= (ArrayList<Order>) eatery.getOrdersByRestaurant(restaurantId);
        this.orderedFood=new ArrayList<>();
         btnProcessOrder.setVisible(false);
            btnCancelOrder.setVisible(false);
            this.getContentPane().setBackground(new Color(0,153,204));
        populateOrders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFood = new javax.swing.JTable();
        btnProcessOrder = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnViewFood = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Food Name", "Price", "Quantity Placed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFood);

        btnProcessOrder.setBackground(new java.awt.Color(102, 102, 102));
        btnProcessOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProcessOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnProcessOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order-processed.png"))); // NOI18N
        btnProcessOrder.setText("Process Order");
        btnProcessOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessOrderActionPerformed(evt);
            }
        });

        btnCancelOrder.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order.png"))); // NOI18N
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE ORDER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Current Orders");

        btnViewFood.setBackground(new java.awt.Color(102, 102, 102));
        btnViewFood.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewFood.setForeground(new java.awt.Color(255, 255, 255));
        btnViewFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        btnViewFood.setText("View Ordered Food");
        btnViewFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewFoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewFoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewFoodMouseExited(evt);
            }
        });
        btnViewFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFoodActionPerformed(evt);
            }
        });

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "OrderId", "Price", "Customer Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrders);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(542, 542, 542)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnViewFood))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProcessOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel2)))
                .addContainerGap(541, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnViewFood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcessOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessOrderActionPerformed
        // TODO add your handling code here:
        int col= 0;
        int row=tblOrders.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "You should select atleast 1 row to update!");
        } else {
        int OrderId= Integer.parseInt(tblOrders.getModel().getValueAt(row, col).toString());
        eatery.processOrderByRestaurant(OrderId);
        resOrders=(ArrayList<Order>) eatery.getOrdersByRestaurant(currentRestaurantId);
        orderedFood.clear();
        populateOrders();
        populateFoodList();
        }
    }//GEN-LAST:event_btnProcessOrderActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        // TODO add your handling code here:
        int col= 0;
        int row=tblOrders.getSelectedRow();
        
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "You should select atleast 1 row to update!");
        } else {
         int OrderId= Integer.parseInt(tblOrders.getModel().getValueAt(row, col).toString());
        Order ord = eatery.getOrderWithOrderId(OrderId);
        eatery.cancelOrderByRestaurant(currentRestaurantId,OrderId);
        resOrders=(ArrayList<Order>) eatery.getOrdersByRestaurant(currentRestaurantId);
        orderedFood.clear();
        populateOrders();
        populateFoodList();
        }
       
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void btnViewFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFoodActionPerformed
        // TODO add your handling code here:
           int col= 0;
        int row=tblOrders.getSelectedRow();
        
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "You should select atleast 1 row to update!");
        } else {
         int OrderId= Integer.parseInt(tblOrders.getModel().getValueAt(row, col).toString());
         Order order = eatery.getOrderWithOrderId(OrderId);
         orderedFood=order.getOrderedFoodList();
         if(orderedFood.size()>0)
         {
            populateFoodList(); 
            btnProcessOrder.setVisible(true);
            btnCancelOrder.setVisible(true);
         }
         
        }
    }//GEN-LAST:event_btnViewFoodActionPerformed

    private void btnViewFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewFoodMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewFoodMouseClicked

    private void btnViewFoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewFoodMouseEntered
        // TODO add your handling code here:
        btnViewFood.setBackground(new Color(255,204,0));

    }//GEN-LAST:event_btnViewFoodMouseEntered

    private void btnViewFoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewFoodMouseExited
        // TODO add your handling code here:
        btnViewFood.setBackground(new Color(102,102,102));

    }//GEN-LAST:event_btnViewFoodMouseExited
private void populateOrders() 
     {
    
         tblOrders.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel tableModel = (DefaultTableModel) tblOrders.getModel();
        tableModel.setRowCount(0);
        if (resOrders!=null) {
            for (int i = 0; i < resOrders.size(); i++) {
                Order o = resOrders.get(i);
                Object[] tableRow = new Object[10];
                tableRow[0] = o.getOrderId();
                tableRow[1]= o.getTotalPrice();
                tableRow[2] = o.getCustomerId();
                tableModel.addRow(tableRow);
            }
        }
         
     }

private void populateFoodList() 
     {
    
         tblFood.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel tableModel = (DefaultTableModel) tblFood.getModel();
        tableModel.setRowCount(0);
        if (orderedFood!=null) {
            for (int i = 0; i < orderedFood.size(); i++) {
                Food o = orderedFood.get(i);
                Object[] tableRow = new Object[10];
                tableRow[0] = o.getName();
                tableRow[1]= o.getPrice();
                tableRow[2] = o.getQuantity();
                tableModel.addRow(tableRow);
            }
        }
         
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderManagerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderManagerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderManagerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderManagerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new orderManagerPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnProcessOrder;
    private javax.swing.JButton btnViewFood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFood;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}
