/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.restaurantFrame;

import java.awt.Color;
import javax.swing.JFrame;
import model.EateryEnterprise;
import ui.systemAdmin.systemAdminLogin;

/**
 *
 * @author BARATHI
 */
public class restaurantLanding extends javax.swing.JFrame {

    /**
     * Creates new form restaurantLanding
     */
     private EateryEnterprise eatery;
       
    public restaurantLanding(EateryEnterprise eatery) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.eatery=eatery;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenuManagement = new javax.swing.JButton();
        btnEmployeeManagement = new javax.swing.JButton();
        btnOrderManagement = new javax.swing.JButton();
        btnSystemAdminFrame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenuManagement.setBackground(new java.awt.Color(102, 102, 102));
        btnMenuManagement.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        btnMenuManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online-order.png"))); // NOI18N
        btnMenuManagement.setText("MENU MANAGEMENT");
        btnMenuManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuManagementMouseExited(evt);
            }
        });
        btnMenuManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuManagementActionPerformed(evt);
            }
        });

        btnEmployeeManagement.setBackground(new java.awt.Color(102, 102, 102));
        btnEmployeeManagement.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        btnEmployeeManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployeeManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team-management.png"))); // NOI18N
        btnEmployeeManagement.setText("EMPLOYEE MANAGEMENT");
        btnEmployeeManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmployeeManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmployeeManagementMouseExited(evt);
            }
        });
        btnEmployeeManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeManagementActionPerformed(evt);
            }
        });

        btnOrderManagement.setBackground(new java.awt.Color(102, 102, 102));
        btnOrderManagement.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        btnOrderManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logistic.png"))); // NOI18N
        btnOrderManagement.setText("ORDER DELIVERY MANAGEMENT");
        btnOrderManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrderManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrderManagementMouseExited(evt);
            }
        });
        btnOrderManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderManagementActionPerformed(evt);
            }
        });

        btnSystemAdminFrame.setBackground(new java.awt.Color(102, 102, 102));
        btnSystemAdminFrame.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        btnSystemAdminFrame.setForeground(new java.awt.Color(255, 255, 255));
        btnSystemAdminFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/software-engineer.png"))); // NOI18N
        btnSystemAdminFrame.setText("RESTAURANT  ADMINISTRATOR");
        btnSystemAdminFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSystemAdminFrameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSystemAdminFrameMouseExited(evt);
            }
        });
        btnSystemAdminFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemAdminFrameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESTAURANT ENTERPRISE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PLEASE CLICK THE APPROPRIATE BUTTON, TO CONTINUE");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTERPRISE LEVEL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESTAURANT SPECIFIC");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restaurantGif.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnOrderManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnEmployeeManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnMenuManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(315, 315, 315))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(327, 327, 327)
                                .addComponent(btnSystemAdminFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnSystemAdminFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOrderManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEmployeeManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenuManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuManagementActionPerformed
        // TODO add your handling code here:
        menuManagerLogin menuManagerLogin = new menuManagerLogin(eatery);
        menuManagerLogin.setVisible(true);
    }//GEN-LAST:event_btnMenuManagementActionPerformed

    private void btnEmployeeManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeManagementActionPerformed
        // TODO add your handling code here:
        employeeManagerLogin empManageLogin = new employeeManagerLogin(eatery);
        empManageLogin.setVisible(true);
    }//GEN-LAST:event_btnEmployeeManagementActionPerformed

    private void btnOrderManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderManagementActionPerformed
        // TODO add your handling code here:
        orderManagerLogin orderManager= new orderManagerLogin(eatery);
        orderManager.setVisible(true);
    }//GEN-LAST:event_btnOrderManagementActionPerformed

    private void btnSystemAdminFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemAdminFrameActionPerformed
        // TODO add your handling code here:
        systemAdminLogin sysadminLogin= new systemAdminLogin(eatery);
        sysadminLogin.setVisible(true);
    }//GEN-LAST:event_btnSystemAdminFrameActionPerformed

    private void btnSystemAdminFrameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSystemAdminFrameMouseEntered
        // TODO add your handling code here:
        btnSystemAdminFrame.setBackground(new Color(255,204,0));

    }//GEN-LAST:event_btnSystemAdminFrameMouseEntered

    private void btnSystemAdminFrameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSystemAdminFrameMouseExited
        // TODO add your handling code here:
        btnSystemAdminFrame.setBackground(new Color(102,102,102));

    }//GEN-LAST:event_btnSystemAdminFrameMouseExited

    private void btnOrderManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderManagementMouseEntered
        // TODO add your handling code here:
        btnOrderManagement.setBackground(new Color(255,204,0));

    }//GEN-LAST:event_btnOrderManagementMouseEntered

    private void btnOrderManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderManagementMouseExited
        // TODO add your handling code here:
        btnOrderManagement.setBackground(new Color(102,102,102));

    }//GEN-LAST:event_btnOrderManagementMouseExited

    private void btnEmployeeManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeManagementMouseEntered
        // TODO add your handling code here:
        btnEmployeeManagement.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_btnEmployeeManagementMouseEntered

    private void btnEmployeeManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeManagementMouseExited
        // TODO add your handling code here:
        btnEmployeeManagement.setBackground(new Color(102,102,102));

    }//GEN-LAST:event_btnEmployeeManagementMouseExited

    private void btnMenuManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuManagementMouseEntered
        // TODO add your handling code here:
        btnMenuManagement.setBackground(new Color(255,204,0));

    }//GEN-LAST:event_btnMenuManagementMouseEntered

    private void btnMenuManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuManagementMouseExited
        // TODO add your handling code here:
        btnMenuManagement.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btnMenuManagementMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(restaurantLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(restaurantLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(restaurantLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(restaurantLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new restaurantLanding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployeeManagement;
    private javax.swing.JButton btnMenuManagement;
    private javax.swing.JButton btnOrderManagement;
    private javax.swing.JButton btnSystemAdminFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
