/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customerFrame;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.EateryEnterprise;
import model.Food;
import model.Order;

/**
 *
 * @author ktkir
 */
public class customerPastOrders extends javax.swing.JPanel {

    /**
     * Creates new form customerPastOrders
     */
    EateryEnterprise eatery;
    Customer currentCustomer;
    List<Order> pastOrders;
    public customerPastOrders(EateryEnterprise eatery,Customer currentCustomer) {
        initComponents();
        this.eatery=eatery;
        this.currentCustomer=currentCustomer;
        this.pastOrders=new ArrayList<>();
        this.pastOrders=currentCustomer.getPastOrders();
        populatePastOrdersTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pastOrdersTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        pastOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order Id", "Restaraunt Id", "Delivery Person Id", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(pastOrdersTable);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PAST ORDERS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populatePastOrdersTable(){
        pastOrdersTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel tableModel = (DefaultTableModel) pastOrdersTable.getModel();
        tableModel.setRowCount(0);
        if (pastOrders!=null) {
            for (int i = 0; i < pastOrders.size(); i++) {
                Order ord = pastOrders.get(i);
                Object[] tableRow = new Object[10];
                tableRow[0] = ord.getOrderId();
                tableRow[1] = ord.getRestaurantId();
                tableRow[2]= ord.getDeliveryPersonId();
                tableRow[3]= ord.getTotalPrice();
                tableModel.addRow(tableRow);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pastOrdersTable;
    // End of variables declaration//GEN-END:variables
}
