/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.customerFrame;

import java.awt.Color;
import javax.swing.JFrame;
import model.Customer;
import model.EateryEnterprise;

/**
 *
 * @author ktkir
 */
public class customerPortal extends javax.swing.JFrame {

    /**
     * Creates new form customerPortal
     */
    
    EateryEnterprise eatery;
    Customer currentCustomer;
    public customerPortal(EateryEnterprise eatery,Customer customer) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.eatery=eatery;
        this.currentCustomer=customer;
        this.eatery.populateOrdersToCustomer(customer.getStateId());
        welcomeLabel.setText("Welcome! "+currentCustomer.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        splittedPane = new javax.swing.JSplitPane();
        displayPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        togglePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnPastOrders = new javax.swing.JButton();
        currentOrderScreen = new javax.swing.JButton();
        btnEditProfile = new javax.swing.JButton();
        btnGroceryOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        splittedPane.setDividerLocation(200);

        displayPanel.setBackground(new java.awt.Color(0, 153, 204));

        welcomeLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Welcome to your portal. You can order your food, your groceries, view your past orders, current order details and also edit your profiel in this page.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Why are you waiting get going!");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(1420, 1420, 1420)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3))
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 450, Short.MAX_VALUE))
        );

        splittedPane.setRightComponent(displayPanel);

        togglePanel.setBackground(new java.awt.Color(0, 153, 204));
        togglePanel.setPreferredSize(new java.awt.Dimension(300, 596));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delivery.png"))); // NOI18N
        jButton1.setText("MAKE FOOD ORDER");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPastOrders.setBackground(new java.awt.Color(102, 102, 102));
        btnPastOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnPastOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/past.png"))); // NOI18N
        btnPastOrders.setText("PAST ORDERS");
        btnPastOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPastOrdersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPastOrdersMouseExited(evt);
            }
        });
        btnPastOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastOrdersActionPerformed(evt);
            }
        });

        currentOrderScreen.setBackground(new java.awt.Color(102, 102, 102));
        currentOrderScreen.setForeground(new java.awt.Color(255, 255, 255));
        currentOrderScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flash.png"))); // NOI18N
        currentOrderScreen.setText("CURRENT ORDER");
        currentOrderScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                currentOrderScreenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                currentOrderScreenMouseExited(evt);
            }
        });
        currentOrderScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentOrderScreenActionPerformed(evt);
            }
        });

        btnEditProfile.setBackground(new java.awt.Color(102, 102, 102));
        btnEditProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnEditProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        btnEditProfile.setText("EDIT PROFILE");
        btnEditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditProfileMouseExited(evt);
            }
        });
        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });

        btnGroceryOrder.setBackground(new java.awt.Color(102, 102, 102));
        btnGroceryOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnGroceryOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grocery.png"))); // NOI18N
        btnGroceryOrder.setText("MAKE GROCERY ORDER");
        btnGroceryOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroceryOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroceryOrderMouseExited(evt);
            }
        });
        btnGroceryOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroceryOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout togglePanelLayout = new javax.swing.GroupLayout(togglePanel);
        togglePanel.setLayout(togglePanelLayout);
        togglePanelLayout.setHorizontalGroup(
            togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(togglePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGroceryOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPastOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentOrderScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        togglePanelLayout.setVerticalGroup(
            togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(togglePanelLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnGroceryOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPastOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(currentOrderScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditProfile)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        togglePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditProfile, btnPastOrders, currentOrderScreen, jButton1});

        splittedPane.setLeftComponent(togglePanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splittedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1642, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splittedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_formWindowClosed

    private void btnGroceryOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroceryOrderActionPerformed
        // TODO add your handling code here:
        customerGroceryOrder custGrocery = new customerGroceryOrder(eatery,currentCustomer );
        splittedPane.setRightComponent(custGrocery);
    }//GEN-LAST:event_btnGroceryOrderActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
        // TODO add your handling code here:
        CustomerProfile cp=new CustomerProfile(eatery,currentCustomer);
        splittedPane.setRightComponent(cp);

    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void currentOrderScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentOrderScreenActionPerformed
        // TODO add your handling code here:
        customerCurrentOrder custCurrent = new customerCurrentOrder(eatery,currentCustomer);
        splittedPane.setRightComponent(custCurrent);
    }//GEN-LAST:event_currentOrderScreenActionPerformed

    private void btnPastOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastOrdersActionPerformed
        // TODO add your handling code here:
        customerPastOrders custPast = new customerPastOrders(eatery,currentCustomer );
        splittedPane.setRightComponent(custPast);
    }//GEN-LAST:event_btnPastOrdersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        customerFoodOrder custOrder= new customerFoodOrder(eatery,currentCustomer);
        splittedPane.setRightComponent(custOrder);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton1MouseExited

    private void btnGroceryOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroceryOrderMouseEntered
        // TODO add your handling code here:
        btnGroceryOrder.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_btnGroceryOrderMouseEntered

    private void btnGroceryOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroceryOrderMouseExited
        // TODO add your handling code here:
        btnGroceryOrder.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btnGroceryOrderMouseExited

    private void btnPastOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPastOrdersMouseEntered
        // TODO add your handling code here:
        btnPastOrders.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_btnPastOrdersMouseEntered

    private void btnPastOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPastOrdersMouseExited
        // TODO add your handling code here:
         btnPastOrders.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btnPastOrdersMouseExited

    private void currentOrderScreenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentOrderScreenMouseEntered
        // TODO add your handling code here:
        currentOrderScreen.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_currentOrderScreenMouseEntered

    private void currentOrderScreenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentOrderScreenMouseExited
        // TODO add your handling code here:
         currentOrderScreen.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_currentOrderScreenMouseExited

    private void btnEditProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditProfileMouseEntered
        // TODO add your handling code here:
        btnEditProfile.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_btnEditProfileMouseEntered

    private void btnEditProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditProfileMouseExited
        // TODO add your handling code here:
        btnEditProfile.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btnEditProfileMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new customerPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnGroceryOrder;
    private javax.swing.JButton btnPastOrders;
    private javax.swing.JButton currentOrderScreen;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane splittedPane;
    private javax.swing.JPanel togglePanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
