/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.DeliveryPartnerEnterprise;
import model.EateryCustomerManagement;
import model.EateryEnterprise;
import model.GroceryEnterprise;
import model.OrderDirectory;
import model.RestaurantEnterprise;
import ui.customerFrame.CustomerLogin;
import ui.customerFrame.CustomerManageFrame;
import ui.deliveryPersonFrame.deliveryLanding;
import ui.groceriesFrame.GroceriesLogin;
import ui.restaurantFrame.restaurantLanding;
import ui.systemAdmin.systemAdminLogin;

/**
 *
 * @author ktkir
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    
    
        private EateryCustomerManagement eatCusManage;
    private RestaurantEnterprise restarauntManagement;
    private DeliveryPartnerEnterprise deliveryEnterPrise;
    private OrderDirectory orderList;
    private EateryEnterprise eatery;
    private GroceryEnterprise groceryenterprise;
    
    public mainFrame() {
        initComponents();
        eatCusManage=new EateryCustomerManagement();
        restarauntManagement=new RestaurantEnterprise();
        deliveryEnterPrise=new DeliveryPartnerEnterprise();
        groceryenterprise = new GroceryEnterprise();
        orderList=new OrderDirectory();
        eatery= new EateryEnterprise(eatCusManage,restarauntManagement,deliveryEnterPrise,orderList,groceryenterprise);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSystemAdminFrame = new javax.swing.JButton();
        btnCustomerFrame = new javax.swing.JButton();
        btnDeliveryPersonFrame = new javax.swing.JButton();
        btnRestarauntFrame = new javax.swing.JButton();
        btnCustomerFrame1 = new javax.swing.JButton();
        btngrocery = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EATERY APPLICATION");

        btnSystemAdminFrame.setBackground(new java.awt.Color(255, 204, 204));
        btnSystemAdminFrame.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnSystemAdminFrame.setText("SYSTEM ADMIN");
        btnSystemAdminFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemAdminFrameActionPerformed(evt);
            }
        });

        btnCustomerFrame.setBackground(new java.awt.Color(255, 255, 0));
        btnCustomerFrame.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnCustomerFrame.setText("Manage Customer");
        btnCustomerFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerFrameActionPerformed(evt);
            }
        });

        btnDeliveryPersonFrame.setBackground(new java.awt.Color(255, 255, 0));
        btnDeliveryPersonFrame.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnDeliveryPersonFrame.setText("DELIVERY BOY");
        btnDeliveryPersonFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryPersonFrameActionPerformed(evt);
            }
        });

        btnRestarauntFrame.setBackground(new java.awt.Color(255, 255, 0));
        btnRestarauntFrame.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnRestarauntFrame.setText("RESTARAUNT");
        btnRestarauntFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarauntFrameActionPerformed(evt);
            }
        });

        btnCustomerFrame1.setBackground(new java.awt.Color(255, 255, 0));
        btnCustomerFrame1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnCustomerFrame1.setText("CUSTOMER");
        btnCustomerFrame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerFrame1ActionPerformed(evt);
            }
        });

        btngrocery.setBackground(new java.awt.Color(255, 255, 0));
        btngrocery.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btngrocery.setText("Grocery");
        btngrocery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngroceryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btngrocery, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomerFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRestarauntFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(btnSystemAdminFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(btnDeliveryPersonFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCustomerFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnSystemAdminFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRestarauntFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeliveryPersonFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnCustomerFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCustomerFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btngrocery, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerFrameActionPerformed
        // TODO add your handling code here:
        CustomerManageFrame cm = new CustomerManageFrame(eatery);
        cm.setVisible(true);
    }//GEN-LAST:event_btnCustomerFrameActionPerformed

    private void btnDeliveryPersonFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryPersonFrameActionPerformed
        // TODO add your handling code here:
        deliveryLanding delMain= new deliveryLanding(eatery);
        delMain.setVisible(true);
    }//GEN-LAST:event_btnDeliveryPersonFrameActionPerformed

    private void btnSystemAdminFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemAdminFrameActionPerformed
        // TODO add your handling code here:
   systemAdminLogin sysadminLogin= new systemAdminLogin(eatery);
    sysadminLogin.setVisible(true);
    }//GEN-LAST:event_btnSystemAdminFrameActionPerformed

    private void btnRestarauntFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarauntFrameActionPerformed
        // TODO add your handling code here:
        restaurantLanding restLand = new restaurantLanding(eatery);
        restLand.setVisible(true);
    }//GEN-LAST:event_btnRestarauntFrameActionPerformed

    private void btnCustomerFrame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerFrame1ActionPerformed
        // TODO add your handling code here:
       
        CustomerLogin cl=new CustomerLogin(eatery);
        cl.setVisible(true);
    }//GEN-LAST:event_btnCustomerFrame1ActionPerformed

    private void btngroceryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngroceryActionPerformed
        // TODO add your handling code here:
        
         GroceriesLogin cl=new GroceriesLogin(eatery);
        cl.setVisible(true);
    }//GEN-LAST:event_btngroceryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerFrame;
    private javax.swing.JButton btnCustomerFrame1;
    private javax.swing.JButton btnDeliveryPersonFrame;
    private javax.swing.JButton btnRestarauntFrame;
    private javax.swing.JButton btnSystemAdminFrame;
    private javax.swing.JButton btngrocery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
